### PR TITLE
add solution

### PR DESCRIPTION
**Pull request by slaybrute**

### CODE REVIEW

**Review by olekskov — CHANGES_REQUESTED** [review]
Major mismatch of solution with requirements:
1) "All data from the public API should be fetched once, and only once, when the Application context is created"
but you solution passes each request to external api
2) "Use MySQL DB in your app."
cannot see any DB used

**Review by Ivan95kos — CHANGES_REQUESTED** [review]
"All data from the public API should be fetched once, and only once, when the Application context is created"
but you solution passes each request to external api

**Comment by slaybrute** [comment]
I've added to internal as well check my last commit please

**Review by Ivan95kos — APPROVED** [review]
Nice!

**Pull request closed without merging**
